app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//入口頁面首頁
Route::get('/', [
    'as' => 'home',
    'uses' => 'HomeController@index'
]);

Route::controller('member', 'MemberController', [
    'getIndex' => 'member.list',
    'getLogin' => 'member.login',
    'postLogin' => 'member.login',
    'getRegister' => 'member.register',
    'postRegister' => 'member.register',
    'getConfirm' => 'member.confirm',
    'getResend' => 'member.resend',
    'postResend' => 'member.resend',
    'getForgotPassword' => 'member.forgot-password',
    'postForgotPassword' => 'member.forgot-password',
    'getResetPassword' => 'member.reset-password',
    'postResetPassword' => 'member.reset-password',
    'getChangePassword' => 'member.change-password',
    'postChangePassword' => 'member.change-password',
    'getProfile' => 'member.profile',
    'getEditProfile' => 'member.edit-profile',
    'postEditProfile' => 'member.edit-profile',
    'getEditOtherProfile' => 'member.edit-other-profile',
    'postEditOtherProfile' => 'member.edit-other-profile',
    'getLogout' => 'member.logout'
]);

//投票系統
Route::post('vote-event/start/{vid}', [
    'as' => 'vote-event.start',
    'uses' => 'VoteEventController@start'
]);
Route::post('vote-event/end/{vid}', [
    'as' => 'vote-event.end',
    'uses' => 'VoteEventController@end'
]);
Route::post('vote-event/sort/{vid}', [
    'as' => 'vote-event.sort',
    'uses' => 'VoteEventController@sort'
]);
Route::resource('vote-event', 'VoteEventController');
Route::post('vote-selection/vote/{id}', [
    'as' => 'vote-selection.vote',
    'uses' => 'VoteSelectionController@vote'
]);
Route::resource('vote-selection', 'VoteSelectionController', ['except' => ['index', 'show']]);
Route::resource('organizer', 'OrganizerController');

//寄送測試信
Route::post('send-test-mail', [
    'as' => 'send-test-mail',
    'uses' => 'SettingController@sendTestMail'
]);

//Queue狀態
Route::get('queue-status', [
    'as' => 'queue-status',
    'uses' => 'QueueStatusController@index'
]);

//網站設定
Route::resource('setting', 'SettingController', ['except' => ['create', 'store', 'destroy']]);

//統計頁面
Route::controller('stats', 'StatsController', [
    'getIndex' => 'stats.index',
    'getForceRenew' => 'stats.force-renew'
]);

//Markdown API
Route::any('markdown', [
    'as' => 'markdown.preview',
    'uses' => 'MarkdownApiController@markdownPreview'
]);

//上傳
Route::controller('upload', 'UploadController', [
    'postImage' => 'upload.image',
    'deleteImage' => 'upload.delete-image'
]);

//Log Viewer
Route::get('log', [
    'as' => 'log',
    'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index',
    'middleware' => 'role:admin'
]);

$policiesTabs = ['privacy', 'terms', 'FAQ'];
Route::get(
    'policies/{tab}',
    [
        'as' => 'policies',
        function ($tab) use ($policiesTabs) {
            if (!in_array($tab, $policiesTabs)) {
                return redirect()->route('policies', $policiesTabs[0]);
            }
            return response()->view('policies');
        }
    ]
);

//未定義路由
Route::get('{all}', [
    'as' => 'not-found',
    function () {
        abort(404);
    }
])->where('all', '.*');

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="zh-Hant">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta property="og:title" content="@if (trim($__env->yieldContent('title'))) @yield('title') - @endif{{ Config::get('config.sitename') }}">
        <meta property="og:url" content="{{ URL::current() }}">
        <meta property="og:image" content="{{ asset('pic/logo.jpg') }}">
        @section('metaTag')
            <meta name="description" property="og:description" content="逢甲票選系統(iVoting) - 一個由學生社團做的票選系統，快來參加各種票選活動吧！！！">
        @show

        <title>@if (trim($__env->yieldContent('title'))) @yield('title') - @endif{{ Config::get('config.sitename') }}</title>

        {{-- Bootstrap United Theme--}}
        {!! HTML::style('//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/united/bootstrap.min.css') !!}
        {{-- 提供超多好看的Icon --}}
        {!! HTML::style('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css') !!}

        {!! Minify::stylesheet([
            '/css/stylesheet.css',            // 全域自訂 CSS
            '/css/sticky-footer.css',         // 頁尾資訊
            '/css/animate.css',               // 給 bootstrap-notify 使用，用來彈出訊息框的淡入淡出特效
            '/css/tipped.css',                // 好看的提示框
        ])->withFullUrl() !!}

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            {!! HTML::script('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js') !!}
            {!! HTML::script('https://oss.maxcdn.com/respond/1.4.2/respond.min.js') !!}
        <![endif]-->

        @yield('css')

        @yield('head-javascript')
    </head>
    <body>
        {{-- navbar--}}
        @include('common.navbar')

        @if(!empty(App\Setting::get('global-notice')))
            <div class="container">
                <div class="alert alert-warning" role="alert">
                    {!! App\Setting::get('global-notice') !!}
                </div>
            </div>
        @endif

        {{-- 信箱未驗證提示--}}
        @if(Auth::check() && !Auth::user()->isConfirmed())
            <div class="container">
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-alert"></span> <b>請注意：</b>
                    您的帳號尚未完成{!! link_to_route('member.resend','Email驗證') !!}，可使用功能依然受限。
                    請盡快完成{!! link_to_route('member.resend','Email驗證') !!}，否則帳號將於 <span title="{{ (new Carbon(Auth::user()->created_at))->hour(5)->minute(30)->addMonth()->diffForHumans(Carbon::now())}}">{{ (new Carbon(Auth::user()->created_at))->hour(5)->minute(30)->addMonth()->formatLocalized('%Y-%m-%d') }}</span> 自動刪除。
                </div>
            </div>
        @endif

        @yield('main-jumbotron')

        {{-- content --}}
        @yield('content')

        <footer class="footer">
            <div class="container">
                <p class="text-muted">
                    Powered by <a href="https://hackersir.info" target="_blank">逢甲大學黑客社</a>
                </p>
                <ol class="breadcrumb" style="padding-top: 0; margin-bottom: 0px;">
                    <li><a href="{{ URL::route('policies', 'privacy') }}">隱私權</a></li>
                    <li><a href="{{ URL::route('policies', 'terms') }}">服務條款</a></li>
                    <li><a href="{{ URL::route('policies', 'FAQ') }}">常見問題</a></li>
                    <li><a href="mailto:{{ urlencode('"逢甲票選系統"') }}<ifcu.ivoting@gmail.com>" target="_blank"><span class="glyphicon glyphicon-envelope" aria-hidden="true" style="margin-right: 5px;"></span>聯絡我們</a></li>
                    @if(env('Report_URL'))
                        <li><a href="{{ env('Report_URL') }}" target="_blank"><span class="glyphicon glyphicon-pencil" aria-hidden="true" style="margin-right: 5px;"></span>回報問題</a></li>
                    @endif
                    @if(Entrust::hasRole('admin'))
                        <li><a href="{{ URL::route('stats.index') }}"><span class="glyphicon glyphicon-stats" aria-hidden="true" style="margin-right: 5px;"></span>統計</a></li>
                    @endif
                </ol>
            </div>
        </footer>

        <!-- Scripts -->
        {!! HTML::script('//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js') !!}
        {!! HTML::script('//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js') !!}
        {{-- 好看的提示框 --}}
        {!! Minify::javascript('/js/tipped.js')->withFullUrl() !!}
        {{-- 好看的彈出訊息框 --}}
        {!! HTML::script('js/bootstrap-notify.min.js') !!}
        {!! HTML::script('js/notify.js') !!}

        @if(App::environment('production'))
            {!! HTML::script('js/analyticstracking.js') !!}
        @endif

        @yield('javascript')

        <script type="text/javascript">
            @if(Session::has('global'))
                /* Global message */
                notifySuccess('{!! Session::get('global') !!}');
            @endif
            @if(Session::has('warning'))
                /* Warning message */
                notifyWarning('{!! Session::get('warning') !!}', '{{ Session::get('delay', 0) }}');
            @endif

            $(document).ready(function() {
                Tipped.create('*',{
                    fadeIn: 0,
                    fadeOut: 0,
                    position: 'right',
                    target: 'mouse',
                    showDelay: 0,
                    hideDelay: 0,
                    offset: { x: 0, y: 15 },
                    stem: false
                });
            });
        </script>
    </body>
</html>

resources/views/home.blade.php
@extends('app')

@section('main-jumbotron')
    <div class="container">
        <div class="row">
            <div class="col-sm-8 jumbotron">
                <h1>{{ Config::get('config.sitename') }}</h1>

                <p>一個由學生社團做的票選系統，快來參加各種票選活動吧！！！</p>

                <p><a href="{{ URL::route('vote-event.index') }}" class="btn btn-primary btn-lg">查看票選活動 »</a></p>
            </div>
            <div class="col-sm-4 hidden-xs">
                <img src="{{ asset('pic/logo.png') }}" style="float: right; height: 400px" />
            </div>
        </div>
    </div>
@endsection

@section('content')
    <div class="container container-background">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="text-center">如何投票</h1>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-4">
                @if(Auth::guest())
                    <a href="{{ URL::route('member.login') }}" style="color: black;">
                @endif
                        <div class="text-center">
                            <span class="glyphicon glyphicon-log-in text-info" style="font-size: 150px;"></span>
                        </div>
                        <h2 class="text-center">登入票選網站</h2>
                @if(Auth::guest())
                    </a>
                @endif
            </div>
            <div class="col-sm-4">
                <a href="{{ URL::route('vote-event.index') }}" style="color: black;">
                    <div class="text-center">
                        <span class="glyphicon glyphicon-list-alt text-info" style="font-size: 150px;"></span>
                    </div>
                    <h2 class="text-center">瀏覽投票活動</h2>
                </a>
            </div>
            <div class="col-sm-4">
                <div class="text-center">
                    {{-- padding-right: 15px; 是要讓圖案往右移一些，用手機看起來會好點 --}}
                    <span class="glyphicon glyphicon-check text-info" style="font-size: 150px; padding-left: 15px;"></span>
                </div>
                <h2 class="text-center">投下神聖的一票</h2>
            </div>
        </div>
    </div>
@endsection

resources/views/policies.blade.php
@extends('app')

@section('css')
    <style type="text/css">
        @media
        only screen and (min-width: 768px) {
            .custom {
                font-size: larger;
            }
        }
    </style>
@endsection

@section('content')
    <div class="container container-background">
        <ul class="nav nav-tabs">
            <li role="presentation" @if(Request::is('policies/privacy')) class="active" @endif>
                <a href="{{ URL::route('policies', 'privacy') }}">隱私權</a>
            </li>
            <li role="presentation" @if(Request::is('policies/terms')) class="active" @endif>
                <a href="{{ URL::route('policies', 'terms') }}">服務條款</a>
            </li>
            <li role="presentation" @if(Request::is('policies/FAQ')) class="active" @endif>
                <a href="{{ URL::route('policies', 'FAQ') }}">常見問題</a>
            </li>
        </ul>
        <div class="panel panel-default">
            <div class="panel-body custom">
                @if(Request::is('policies/privacy'))
                    {!! App\Helper\MarkdownHelper::translate(File::get('privacy.md'), ['autoLineBreak' => false]) !!}
                @elseif(Request::is('policies/terms'))
                    {!! App\Helper\MarkdownHelper::translate(File::get('terms.md'), ['autoLineBreak' => false]) !!}
                @elseif(Request::is('policies/FAQ'))
                    {!! App\Helper\MarkdownHelper::translate(File::get('faq.md'), ['autoLineBreak' => false]) !!}
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/queue-status.blade.php
@extends('app')

@section('css')
    <style type="text/css">
        .popover {
            max-width: 50%;
            width: auto;
            word-break: break-all;
        }
    </style>
@endsection

@section('content')
    <div class="container container-background">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Queue Status (All)</h3>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="col-md-3">Name</th>
                    <th class="col-md-6">Description</th>
                    <th class="col-md-3">State</th>
                </tr>
                </thead>
                <tbody>
                @if(is_array($queues))
                    @forelse($queues as $queue)
                        <tr>
                            <td>{{ $queue['name'] }}</td>
                            <td>{{ $queue['description'] }}</td>
                            <td>{{ $queue['state'] }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td class="text-center" colspan="3">沒有資料</td>
                        </tr>
                    @endforelse
                @else
                    <tr>
                        <td class="text-center" colspan="3">{{ $queues }}</td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Jobs Queue (Count: {{ $jobCount }})</h3>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="col-md-1 text-center">#</th>
                    <th class="col-md-1">Queue</th>
                    <th class="col-md-8">Payload</th>
                    <th class="col-md-2 text-center">建立時間</th>
                </tr>
                </thead>
                <tbody>
                @forelse($jobs as $job)
                    <tr>
                        <td class="text-center">{{ $job->id }}</td>
                        <td>{{ $job->queue }}</td>
                        @if(strlen($job->payload) <= 100)
                            <td>{{ $job->payload }}</td>
                        @else
                            <td style="cursor: pointer;" data-toggle="popover" data-placement="bottom" data-content="{{ $job->payload }}">
                                {{ mb_strimwidth($job->payload, 0, 100, "...") }}
                            </td>
                        @endif
                        <td class="text-center">{{ date('Y-m-d H:i:s', $job->created_at) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td  class="text-center" colspan="4">沒有資料</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Failed Jobs (Count: {{ $failedJobCount }})</h3>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="col-md-1 text-center">#</th>
                    <th class="col-md-2">Connection</th>
                    <th class="col-md-1">Queue</th>
                    <th class="col-md-6">Payload</th>
                    <th class="col-md-2 text-center">失敗時間</th>
                </tr>
                </thead>
                <tbody>
                @forelse($failedJobs as $failedJob)
                    <tr>
                        <td class="text-center">{{ $failedJob->id }}</td>
                        <td>{{ $failedJob->connection }}</td>
                        <td>{{ $failedJob->queue }}</td>
                        @if(strlen($failedJob->payload) <= 100)
                            <td>{{ $failedJob->payload }}</td>
                        @else
                            <td data-toggle="popover" data-placement="bottom" data-content="{{ $failedJob->payload }}">
                                {{ mb_strimwidth($failedJob->payload, 0, 100, "...") }}
                            </td>
                        @endif
                        <td class="text-center">{{ $failedJob->failed_at }}</td>
                    </tr>
                @empty
                    <tr>
                        <td  class="text-center" colspan="5">沒有資料</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(function () {
            $('[data-toggle="popover"]').popover({
                container: 'body'
            })
        })
    </script>
@endsection