app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//入口頁面首頁
Route::get('/', [
    'as' => 'home',
    'uses' => 'HomeController@index'
]);

Route::controller('member', 'MemberController', [
    'getIndex' => 'member.list',
    'getLogin' => 'member.login',
    'postLogin' => 'member.login',
    'getRegister' => 'member.register',
    'postRegister' => 'member.register',
    'getConfirm' => 'member.confirm',
    'getResend' => 'member.resend',
    'postResend' => 'member.resend',
    'getForgotPassword' => 'member.forgot-password',
    'postForgotPassword' => 'member.forgot-password',
    'getResetPassword' => 'member.reset-password',
    'postResetPassword' => 'member.reset-password',
    'getChangePassword' => 'member.change-password',
    'postChangePassword' => 'member.change-password',
    'getProfile' => 'member.profile',
    'getEditProfile' => 'member.edit-profile',
    'postEditProfile' => 'member.edit-profile',
    'getEditOtherProfile' => 'member.edit-other-profile',
    'postEditOtherProfile' => 'member.edit-other-profile',
    'getLogout' => 'member.logout'
]);

//投票系統
Route::post('vote-event/start/{vid}', [
    'as' => 'vote-event.start',
    'uses' => 'VoteEventController@start'
]);
Route::post('vote-event/end/{vid}', [
    'as' => 'vote-event.end',
    'uses' => 'VoteEventController@end'
]);
Route::post('vote-event/sort/{vid}', [
    'as' => 'vote-event.sort',
    'uses' => 'VoteEventController@sort'
]);
Route::resource('vote-event', 'VoteEventController');
Route::post('vote-selection/vote/{id}', [
    'as' => 'vote-selection.vote',
    'uses' => 'VoteSelectionController@vote'
]);
Route::resource('vote-selection', 'VoteSelectionController', ['except' => ['index', 'show']]);
Route::resource('organizer', 'OrganizerController');

//寄送測試信
Route::post('send-test-mail', [
    'as' => 'send-test-mail',
    'uses' => 'SettingController@sendTestMail'
]);

//Queue狀態
Route::get('queue-status', [
    'as' => 'queue-status',
    'uses' => 'QueueStatusController@index'
]);

//網站設定
Route::resource('setting', 'SettingController', ['except' => ['create', 'store', 'destroy']]);

//統計頁面
Route::controller('stats', 'StatsController', [
    'getIndex' => 'stats.index',
    'getForceRenew' => 'stats.force-renew'
]);

//Markdown API
Route::any('markdown', [
    'as' => 'markdown.preview',
    'uses' => 'MarkdownApiController@markdownPreview'
]);

//上傳
Route::controller('upload', 'UploadController', [
    'postImage' => 'upload.image',
    'deleteImage' => 'upload.delete-image'
]);

//Log Viewer
Route::get('log', [
    'as' => 'log',
    'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index',
    'middleware' => 'role:admin'
]);

$policiesTabs = ['privacy', 'terms', 'FAQ'];
Route::get(
    'policies/{tab}',
    [
        'as' => 'policies',
        function ($tab) use ($policiesTabs) {
            if (!in_array($tab, $policiesTabs)) {
                return redirect()->route('policies', $policiesTabs[0]);
            }
            return response()->view('policies');
        }
    ]
);

//未定義路由
Route::get('{all}', [
    'as' => 'not-found',
    function () {
        abort(404);
    }
])->where('all', '.*');

resources/views/vote/event/create.blade.php
@extends('app')

@section('title')
    新增投票活動
@endsection

@section('css')
    {!! HTML::style('css/bootstrap-datetimepicker.css') !!}
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="well bs-component">
                    {!! Form::open(['route' => 'vote-event.store', 'class' => 'form-horizontal']) !!}
                    <fieldset>
                        <legend>新增投票活動</legend>
                    </fieldset>
                    <div class="form-group has-feedback{{ ($errors->has('subject'))?' has-error':'' }}">
                        <label class="control-label col-md-2" for="subject">投票主題</label>

                        <div class="col-md-9">
                            {!! Form::text('subject', null, ['id' => 'subject', 'placeholder' => '請輸入投票主題', 'class' => 'form-control', 'required']) !!}
                            @if($errors->has('subject'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            <span class="label label-danger">{{ $errors->first('subject') }}</span>@endif
                        </div>
                    </div>
                    <div class="form-group has-feedback{{ ($errors->has('open_time'))?' has-error':'' }}">
                        <label class="control-label col-md-2" for="open_time">開始時間</label>

                        <div class="col-md-9">
                            <div class='input-group date' id='datetimepicker1'>
                                {!! Form::text('open_time', null, ['id' => 'open_time', 'placeholder' => 'YYYY/MM/DD HH:mm:ss', 'class' => 'form-control']) !!}
                                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                            </div>
                            @if($errors->has('open_time'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            <span class="label label-danger">{{ $errors->first('open_time') }}</span>@endif
                        </div>
                    </div>
                    <div class="form-group has-feedback{{ ($errors->has('close_time'))?' has-error':'' }}">
                        <label class="control-label col-md-2" for="close_time">結束時間</label>

                        <div class="col-md-9">
                            <div class='input-group date' id='datetimepicker2'>
                                {!! Form::text('close_time', null, ['id' => 'close_time', 'placeholder' => 'YYYY/MM/DD HH:mm:ss', 'class' => 'form-control']) !!}
                                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                            </div>
                            @if($errors->has('close_time'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            <span class="label label-danger">{{ $errors->first('close_time') }}</span>@endif
                        </div>
                    </div>
                    <div class="form-group has-feedback{{ ($errors->has('award_count'))?' has-error':'' }}">
                        <label class="control-label col-md-2" for="award_count">選出名額</label>

                        <div class="col-md-9">
                            {!! Form::number('award_count', null, ['id' => 'award_count', 'placeholder' => '活動選出的名額，預設為1', 'class' => 'form-control', 'min' => 1]) !!}
                            @if($errors->has('award_count'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            <span class="label label-danger">{{ $errors->first('award_count') }}</span>@endif
                        </div>
                    </div>
                    <div class="form-group has-feedback{{ ($errors->has('max_selected'))?' has-error':'' }}">
                        <label class="control-label col-md-2" for="max_selected">最多可選幾項</label>

                        <div class="col-md-9">
                            {!! Form::number('max_selected', null, ['id' => 'max_selected', 'placeholder' => '每人最多可選擇之數量，預設為1', 'class' => 'form-control', 'min' => 1]) !!}
                            @if($errors->has('max_selected'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            <span class="label label-danger">{{ $errors->first('max_selected') }}</span>@endif
                        </div>
                    </div>
                    <div class="form-group has-feedback{{ ($errors->has('organizer'))?' has-error':'' }}">
                        <label class="control-label col-md-2" for="organizer">主辦單位</label>

                        <div class="col-md-9">
                            {!! Form::select('organizer', $organizerArray, null, ['class' => 'form-control']) !!}
                            @if($errors->has('organizer'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            <span class="label label-danger">{{ $errors->first('organizer') }}</span>@endif
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2" for="settings">選項</label>

                        <div class="col-md-9">
                            <div class="checkbox">
                                <label>
                                    {!! Form::checkbox('hideVoteEvent', 'true') !!} 在開始前隱藏投票活動
                                </label>
                            </div>

                            <div>
                                <label class="control-label" for="prefix" style="margin-bottom: 5px;">限制學號開頭
                                    <span class="glyphicon glyphicon-question-sign" title="請直接輸入學號開頭，如：d04；<br />若想同時允許多種學號，請用逗號分隔，如：d01,d02。"></span>
                                </label>

                                {!! Form::text('prefix', null, ['id' => 'prefix', 'placeholder' => '只有特定學號開頭可投票，留白為不限制', 'class' => 'form-control']) !!}
                                @if($errors->has('prefix'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                                <span class="label label-danger">{{ $errors->first('prefix') }}</span>@endif
                            </div>
                            <div>
                                <label class="control-label" for="show_result" style="margin-bottom: 5px;">顯示投票結果</label>
                                {!! Form::select('show_result', ['always' => '隨時可以查看票選結果', 'after-vote' => '完成投票者可看見結果（活動結束後對所有人顯示）', 'after-event' => '投票結果將在活動結束後顯示'], 'after-event', ['id' => 'show_result', 'class' => 'form-control']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="form-group has-feedback{{ ($errors->has('info'))?' has-error':'' }}">
                        <label class="control-label col-md-2" for="info">內容簡介</label>

                        <div class="col-md-9" role="tabpanel">
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active"><a href="#edit" aria-controls="edit" role="tab" data-toggle="tab" id="tab_edit">編輯</a></li>
                                <li role="presentation"><a href="#preview" aria-controls="preview" role="tab" data-toggle="tab" id="tab_preview">預覽</a></li>
                            </ul>
                        </div>
                        <div class="col-md-9 col-md-offset-2">
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="edit">
                                    {!! Form::textarea('info', null, [
                                        'id' => 'info',
                                        'placeholder' => '請輸入內容簡介',
                                        'class' => 'form-control',
                                        'style' => 'resize: vertical; font-family: Consolas, monospace;'
                                    ]) !!}
                                    <small>
                                        <b>提示：</b>內容簡介支援{!! link_to('http://markdown.tw/', 'Markdown', ['target' => '_blank']) !!}語法
                                    </small>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="preview" style="background-color: white; border: 1px solid #cccccc; padding: 8px 12px;">
                                </div>
                            </div>
                            @if($errors->has('info'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                            <span class="label label-danger">{{ $errors->first('info') }}</span>@endif
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-2">
                            {!! Form::submit('新增投票活動', ['class' => 'btn btn-primary']) !!}
                            {!! HTML::linkRoute('vote-event.index', '返回', [], ['class' => 'btn btn-default']) !!}
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('javascript')
    {!! HTML::script('//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js') !!}
    {!! Minify::javascript('/js/moment_zh-tw.js')->withFullUrl() !!}
    {!! HTML::script('js/bootstrap-datetimepicker.min.js') !!}
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker({
                format: 'YYYY/MM/DD HH:mm:ss'
            });
            $('#datetimepicker2').datetimepicker({
                format: 'YYYY/MM/DD HH:mm:ss'
            });
        });

        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            // e.target -> newly activated tab
            if (e.target.id == 'tab_preview') {
                $("#preview").html("");

                var URLs = "{{ URL::route('markdown.preview') }}";
                var val = $('#info').val();

                $.ajax({
                    url: URLs,
                    data: val,
                    headers: {
                        'X-CSRF-Token': "{{ Session::token() }}",
                        "Accept": "application/json"
                    },
                    type: "POST",
                    dataType: "text",

                    success: function (data) {
                        if (data) {
                            $("#preview").html((data != " ") ? data : "沒有文字可以預覽。");
                        } else {
                            alert("error");
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
            }
        });

        $('#preview').css('min-height', $('#info').height() + 'px');
    </script>
@endsection

resources/views/vote/event/list.blade.php
@extends('app')

@section('title')
    投票活動清單
@endsection

@section('css')
    {!! HTML::style('css/no-more-table.css') !!}
    <style type="text/css">
        @media
        only screen and (max-width: 479px) {
            /*
            Label the data
            */
            .noMoreTable td:nth-of-type(1):before { content: "狀態"; }
            .noMoreTable td:nth-of-type(2):before { content: "投票主題"; }
            .noMoreTable td:nth-of-type(4):before { content: "開始時間"; }
            .noMoreTable td:nth-of-type(5):before { content: "結束時間"; }
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0">
                <div class="panel panel-default">
                    <div class="panel-heading">票選活動清單</div>
                    {{-- Panel body --}}
                    <div class="panel-body">
                        @if(Auth::check() && Auth::user()->isStaff())
                            {!! HTML::linkRoute('vote-event.create', '新增投票活動', [], ['class' => 'btn btn-primary pull-right']) !!}
                            <div class="clearfix"></div>
                        @endif
                        <table class="table table-hover noMoreTable" style="margin-top: 5px">
                            <thead>
                            <tr>
                                <th class="col-md-1">狀態</th>
                                <th class="col-md-4">投票主題</th>
                                <th></th>
                                <th class="col-md-offset-1 col-md-3">開始時間</th>
                                <th class="col-md-3">結束時間</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($voteEventList as $voteEventItem)
                                @if(Auth::check() && Auth::user()->isStaff() && !$voteEventItem->isVisible())
                                    <tr class="classData danger">
                                @else
                                    <tr class="classData">
                                @endif
                                    <td>
                                        @if($voteEventItem->isEnded())
                                            <span class="label label-warning">已結束</span>
                                        @elseif($voteEventItem->isInProgress())
                                            <span class="label label-success">進行中</span>
                                        @else
                                            <span class="label label-default">未開始</span>
                                        @endif
                                    </td>
                                    <td>{!! HTML::linkRoute('vote-event.show', $voteEventItem->subject, $voteEventItem->id, null) !!}</td>
                                    <td class="hidePhone">
                                        <div class="pull-right">
                                            @if (Auth::check() && Auth::user()->isStaff())
                                                @if(!$voteEventItem->show)
                                                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true" title="活動開始前是不顯示的"></span>
                                                @endif
                                                @if(!$voteEventItem->isEnded())
                                                    <a href="{{ URL::route('vote-event.edit', $voteEventItem->id) }}" title="編輯投票活動"><span class="glyphicon glyphicon-cog" aria-hidden="true" ></span></a>
                                                @endif
                                            @endif
                                        </div>
                                    </td>
                                    <td><span title="{{ (new Carbon($voteEventItem->open_time))->diffForHumans() }}">{{ $voteEventItem->open_time }}</span></td>
                                    <td><span title="{{ (new Carbon($voteEventItem->close_time))->diffForHumans() }}">{{ $voteEventItem->close_time }}</span></td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="text-center">
                            {!! str_replace('/?', '?', $voteEventList->appends(Input::except(array('page')))->render()) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vote/event/show.blade.php
@extends('app')

@section('title')
    {{ $voteEvent->subject }} - 投票活動
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $voteEvent->subject }} - 投票活動</div>
                    {{-- Panel body --}}
                    <div class="panel-body">
                        <div class="row">
                            <div class="text-center col-md-12 col-md-offset-0">
                                <table class="table table-hover">
                                    <tr>
                                        <td class="col-md-2">投票主題：</td>
                                        <td>
                                            {{ $voteEvent->subject }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>狀態：</td>
                                        <td>
                                            @if($voteEvent->isEnded())
                                                已結束
                                            @elseif($voteEvent->isInProgress())
                                                進行中
                                                @if(Auth::check() && Auth::user()->isStaff())
                                                    <br />
                                                    {!! Form::open(['route' => ['vote-event.end', $voteEvent->id], 'style' => 'display: inline', 'method' => 'POST',
                                                    'onSubmit' => "return confirm('確定要立即結束此投票活動嗎？');"]) !!}
                                                    {!! Form::submit('立即結束', ['class' => 'btn btn-danger']) !!}
                                                    {!! Form::close() !!}
                                                @endif
                                            @else
                                                未開始
                                                @if(Auth::check() && Auth::user()->isStaff())
                                                    <br />
                                                    {!! Form::open(['route' => ['vote-event.start', $voteEvent->id], 'style' => 'display: inline', 'method' => 'POST',
                                                    'onSubmit' => "return confirm('確定要立即開始此投票活動嗎？');"]) !!}
                                                    {!! Form::submit('立即開始', ['class' => 'btn btn-danger']) !!}
                                                    {!! Form::close() !!}
                                                @endif
                                            @endif
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>開始時間：</td>
                                        <td>{{ $voteEvent->open_time }}</td>
                                    </tr>
                                    <tr>
                                        <td>結束時間：</td>
                                        <td>{{ $voteEvent->close_time }}</td>
                                    </tr>
                                    <tr>
                                        <td>最多可選幾項：</td>
                                        <td>{{ $voteEvent->getMaxSelected() }}
                                            @if(Auth::check() && Auth::user()->isStaff())
                                                <br />（設定值：{{ $voteEvent->max_selected }}）
                                            @endif
                                        </td>
                                    </tr>
                                </table>
                                <hr />
                                <div class="text-left">
                                    {!! Markdown::parse(htmlspecialchars($voteEvent->info)) !!}
                                </div>
                                <hr />
                                <div>
                                    @if(Auth::check() && Auth::user()->isStaff())
                                        @if(!$voteEvent->isEnded())
                                            {!! HTML::linkRoute('vote-event.edit', '編輯投票活動', $voteEvent->id, ['class' => 'btn btn-primary']) !!}
                                        @endif
                                        {!! HTML::linkRoute('vote-event.index', '返回投票活動列表', [], ['class' => 'btn btn-default']) !!}
                                        @if(!$voteEvent->isStarted())
                                            {!! Form::open(['route' => ['vote-event.destroy', $voteEvent->id], 'style' => 'display: inline', 'method' => 'DELETE',
                                            'onSubmit' => "return confirm('確定要刪除投票活動嗎？');"]) !!}
                                            {!! Form::submit('刪除', ['class' => 'btn btn-danger']) !!}
                                            {!! Form::close() !!}
                                        @endif
                                        @if(Auth::user()->isAdmin())
                                            @if(Request::url() != $autoRedirectSetting->data)
                                                {!! Form::open(['route' => ['setting.update', $autoRedirectSetting->id], 'style' => 'display: inline' ,'class' => 'form-horizontal', 'method' => 'PUT',
                                                'onSubmit' => "return confirm('確定要將此活動設為預設頁面嗎？');"]) !!}
                                                {!! Form::hidden('data', Request::url()) !!}
                                                {!! Form::submit('設為預設', ['class' => 'btn btn-danger', 'title' => '設為進入網站時預設導向之頁面']) !!}
                                                {!! Form::close() !!}
                                            @else
                                                {!! Form::open(['route' => ['setting.update', $autoRedirectSetting->id], 'style' => 'display: inline' ,'class' => 'form-horizontal', 'method' => 'PUT',
                                                'onSubmit' => "return confirm('確定不在將此活動作為預設頁面嗎？');"]) !!}
                                                {!! Form::hidden('data', "") !!}
                                                {!! Form::submit('取消預設', ['class' => 'btn btn-default', 'title' => '取消網站預設導向頁面之設定']) !!}
                                                {!! Form::close() !!}
                                            @endif
                                        @endif
                                    @else
                                        {!! HTML::linkRoute('vote-event.index', '返回投票活動列表', [], ['class' => 'btn btn-default']) !!}
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">投票選項</div>
                    {{-- Panel body --}}
                    <div class="panel-body">
                        <div class="row">
                            <div class="text-center col-md-12 col-md-offset-0">
                                @if(Auth::check() && Auth::user()->isStaff() && !$voteEvent->isStarted())
                                    {!! HTML::linkRoute('vote-selection.create', '新增投票選項', ['vid' => $voteEvent->id], ['class' => 'btn btn-primary pull-right']) !!}
                                @endif
                                <table class="table table-hover">
                                    @if(count($voteEvent->voteSelections))
                                        <thead>
                                            <tr>
                                                @if(Auth::check() && Auth::user()->isStaff() && !$voteEvent->isStarted())
                                                    <th class="col-md-8 text-center">投票項目</th>
                                                    <th class="col-md-4"></th>
                                                @elseif($voteEvent->isEnded())
                                                    <th class="col-md-2 text-center">最高票</th>
                                                    <th class="col-md-8 text-center">投票項目</th>
                                                    <th class="col-md-2 text-center">票數</th>
                                                @else
                                                    <th class="col-md-12 text-center">投票項目</th>
                                                @endif
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($voteEvent->voteSelections as $voteSelectionItem)
                                                <tr>
                                                    @if($voteEvent->isEnded())
                                                        <td class="col-md-2">
                                                            @if($voteSelectionItem->isMax())
                                                                <span title="最高票">♛</span>
                                                            @endif
                                                        </td>
                                                    @endif
                                                    <td>
                                                        @if(Auth::check() && $voteSelectionItem->hasVoted(Auth::user()))
                                                            <span title="我的選擇">✔</span>
                                                        @endif
                                                        {!! HTML::linkRoute('vote-selection.show', $voteSelectionItem->getTitle(),$voteSelectionItem->id, null) !!}
                                                    </td>
                                                    @if(Auth::check() && Auth::user()->isStaff() && !$voteEvent->isStarted())
                                                        <td class="text-right">
                                                            {!! link_to_route('vote-selection.edit', '編輯', $voteSelectionItem->id, ['class' => 'btn btn-default']) !!}
                                                            {!! Form::open(['route' => ['vote-selection.destroy', $voteSelectionItem->id], 'style' => 'display: inline', 'method' => 'DELETE',
                                                            'onSubmit' => "return confirm('確定要刪除此投票選項嗎？');"]) !!}
                                                            {!! Form::submit('刪除', ['class' => 'btn btn-danger']) !!}
                                                            {!! Form::close() !!}
                                                        </td>
                                                    @elseif($voteEvent->isEnded())
                                                        <td class="col-md-2">{{ $voteSelectionItem->getCount() }}</td>
                                                    @endif
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    @else
                                        <tr>
                                            <td>無投票選項</td>
                                        </tr>
                                    @endif
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection